[profile.default]
compiler_version = "0.8.30"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
remappings = ["contract/lib/openzeppelin-contracts/contracts = @openzeppelin/contracts", "@forge/=lib/forge-std/", "@chainlink/contracts=lib/chainlink-evm/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
